[project]
authors = ["Matt McCormick <matt.mccormick@kitware.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "itk-wasm-scipy-paper"
platforms = ["win-64", "linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
start = "myst start"
gen-ome-zarr = "ngff-zarr -c 64 -i ./vm_head_frozenct.mha -o ./vm_head_frozenct.zarr"
naive-downsample = "python ./naive_downsample.py"

[dependencies]
pytest = "*"
python = "3.11.*"

[pypi-dependencies]
itkwasm-image-io = ">=1.3.0, <2"
mystmd = ">=1.3.5, <2"
ngff-zarr = ">=0.8.7, <0.9"
