name: curvenote
on:
  push:
    branches: ['benchmark_paper']
  pull_request_target:
    branches: ['2024']
permissions:
  contents: read
  pull-requests: write
jobs:
  publish:
    uses: curvenote/actions/.github/workflows/publish.yml@v1
    with:
      monorepo: true
      id-pattern-regex: '^scipy-2024-(?:[a-zA-Z0-9-_]{3,25})$'
      enforce-single-folder: paper
      preview-label: paper
      submit-label: true
      venue: scipy
      collection: '2024'
      kind: Article
      path: papers/*
      ref: ${{ github.event.pull_request.head.sha }}
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
      GITHUB: ${{ secrets.GITHUB_TOKEN }}
